CREATE SEQUENCE patient_id_seq;

CREATE TABLE patients (
  ID  INTEGER DEFAULT nextval('patient_id_seq'),
  PID VARCHAR(11) NOT NULL,
  ICD INTEGER NOT NULL,
  SEX INTEGER NOT NULL,
  AGE INTEGER NOT NULL,
  PRIMARY KEY (ID)
);

CREATE INDEX ICD_SEX_AGE ON patients (ICD, SEX, AGE);

CREATE TABLE patient_counts(
  AGE INTEGER NOT NULL,
  SEX INTEGER NOT NULL,
  N INTEGER NOT NULL,
  PRIMARY KEY (AGE)
);
