WITH pid_x AS (
  SELECT DISTINCT PID FROM patients WHERE ICD=5243 AND SEX=1 AND AGE>=10 AND AGE<20 GROUP BY PID
), pid_y AS (
  SELECT DISTINCT PID FROM patients WHERE ICD=7080 AND SEX=1 AND AGE>=10 AND AGE<20 GROUP BY PID
)
SELECT (SELECT COUNT(PID) FROM pid_x) AS kx, (SELECT COUNT(PID) from pid_y) as ky, (SELECT COUNT(pid_x.PID) FROM pid_x, pid_y WHERE pid_x.PID=pid_y.PID) as kxy

SELECT SUM(N)
FROM patient_counts
WHERE AGE>=l AND AGE<h;
